# encoding: UTF-8
$:.unshift(File.dirname(__FILE__))

require 'active_support'
require 'active_support/core_ext'

require 'graticule/version'
require 'graticule/core_ext'
require 'graticule/location'
require 'graticule/precision'
require 'graticule/geocoder'
require 'graticule/geocoder/base'
require 'graticule/geocoder/bogus'
require 'graticule/geocoder/google'
require 'graticule/geocoder/yandex'
require 'graticule/geocoder/host_ip'
require 'graticule/geocoder/multi'
require 'graticule/geocoder/yahoo'
require 'graticule/geocoder/geocoder_ca'
require 'graticule/geocoder/geocoder_us'
require 'graticule/geocoder/geonames'
require 'graticule/geocoder/local_search_maps'
require 'graticule/geocoder/freethepostcode'
require 'graticule/geocoder/multimap'
require 'graticule/geocoder/mapquest'
require 'graticule/geocoder/simple_geo'
require 'graticule/geocoder/mapbox'
require 'graticule/distance'
require 'graticule/distance/haversine'
require 'graticule/distance/spherical'
require 'graticule/distance/vincenty'
